### @name: I hate postman I hate postman I hate postman
POST http://localhost/api/v1/token/pair HTTP/1.1
Content-Type: application/json

{
  "email": "root@root.com",
  "password": "toor"
}

> {%
    client.global.set("access", response.body.access);
%}


###
GET http://localhost/api/v1/debug-celery HTTP/1.1
Content-Type: application/json


###
GET http://localhost/api/v1/docs HTTP/1.1
Content-Type: application/json

###
POST http://localhost/api/v1/csv-files/process/all HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access}}



### Request with client messages
// It is possible to specify client messages in request body. Use '===' to separate messages.
// Add '=== wait-for-server' above a message to send it after a server response is received.
// To wait for N responses, add '=== wait-for-server' N times.
WEBSOCKET ws://localhost/api/v1/ws
Content-Type: application/json

{
  "
  message
  ": "

  Hell
  o,
  s
  rve
}
