version: "3.9"

services:
  caddy:
    image: caddy:2.9.1-alpine
    container_name: caddy
    hostname: caddy
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./api/static:/app/static:ro
      - ./api/media:/app/media:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - bridge

  db:
    image: postgres:17.2-alpine3.21
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./api/secrets/.env
    networks:
      - bridge
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: backend
    hostname: backend
    restart: unless-stopped
    command: >
      sh -c "poetry run python manage.py makemigrations &&
             poetry run python manage.py migrate &&
             poetry run python manage.py collectstatic --noinput &&
             poetry run python uvicorn_config.py"
    environment:
      - WATCHFILES_FORCE_POLLING=true
    env_file:
      - ./api/secrets/.env
    expose:
      - "8000"
    volumes:
      - ./api:/app:z
      - ./api/static:/app/static:z
      - ./api/media:/app/media:z
    depends_on:
      - db
      - redis
    networks:
      - bridge

  redis:
    image: redis:7.4.1
    container_name: redis
    hostname: redis
    restart: unless-stopped
    expose:
      - "6379"
    networks:
      - bridge
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

  celery:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: queue
    hostname: queue
    restart: unless-stopped
    command: poetry run celery -A config worker --loglevel=DEBUG -E --max-tasks-per-child=20 -P threads --concurrency=6
    volumes:
      - ./api:/app:z
      - static_volume:/app/static:z
      - media_volume:/app/media:z
    env_file:
      - ./api/secrets/.env
    networks:
      - bridge
    depends_on:
      - backend
      - redis
      - db

volumes:
  static_volume:
  media_volume:
  pgdata:
  caddy_data:
  caddy_config:

networks:
  bridge:
    driver: bridge
