# Generated by Django 5.1.4 on 2024-12-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvdata",
            name="bg_input",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="csvdata",
            name="bolus",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="csvdata",
            name="carb_input",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="csvdata",
            name="insulin_delivered",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="csvdata",
            name="total_insulin",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
