# Generated by Django 5.1.4 on 2025-01-01 01:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_csvdata_bg_input_csvdata_bolus_csvdata_carb_input_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvdata",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
