# Generated by Django 5.1.4 on 2025-01-15 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0006_alter_csvdata_bg"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvdata",
            name="csv_file",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="data.csvfile"),
            preserve_default=False,
        ),
    ]
