# Generated by Django 5.1.4 on 2025-01-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0007_csvdata_csv_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvdata",
            name="carb_ratio",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="csvdata",
            name="total_basal",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
