# Generated by Django 5.1.4 on 2025-01-19 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0008_csvdata_carb_ratio_csvdata_total_basal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="csvfile",
            name="file_hash",
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="csvfile",
            unique_together={("user", "file_hash")},
        ),
    ]
