# Generated by Django 5.1.5 on 2025-01-26 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_data", models.JSONField(editable=False, null=True, verbose_name="request_data")),
                ("response_data", models.JSONField(editable=False, null=True, verbose_name="response_data")),
                ("user_agent", models.CharField(blank=True, editable=False, max_length=255, verbose_name="user_agent")),
                ("ip_address", models.GenericIPAddressField(editable=False, verbose_name="ip_address")),
                ("path", models.CharField(blank=True, editable=False, max_length=255, verbose_name="path")),
                ("status_code", models.PositiveIntegerField(editable=False, verbose_name="status_code")),
                (
                    "http_method",
                    models.CharField(blank=True, editable=False, max_length=10, verbose_name="http_method"),
                ),
                ("query_params", models.JSONField(editable=False, null=True, verbose_name="query_params")),
                ("timestamp", models.DateTimeField(auto_now_add=True, verbose_name="timestamp")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log",
                "verbose_name_plural": "Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
