name: Create Tag on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  create_tag:
    if: ${{ github.event.pull_request.merged && github.event.pull_request.base.ref == 'main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for accurate changelog

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Use a stable Python version

      - name: Install dependencies
        run: |
          python -m pip install toml

      - name: Extract version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['tool']['poetry']['version'])")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Generate tag name
        id: generate_tag_name
        run: |
          FLAVOUR="-merged-pr-${{ github.event.pull_request.number }}"
          TAG_NAME="${{ steps.get_version.outputs.version }}${FLAVOUR}"
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Get PR Changelog
        id: get_changelog
        run: |
          if [ -z "${{ github.event.pull_request.body }}" ]; then
            echo "No PR body found. Generating changelog from commits."
            git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 @^)..@ > changelog.txt
          else
            echo "${{ github.event.pull_request.body }}" > changelog.txt
          fi

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create and push annotated tag
        run: |
          TAG_NAME="${{ steps.generate_tag_name.outputs.tag_name }}"
          echo "Creating tag $TAG_NAME"
          git tag -a "$TAG_NAME" -F changelog.txt
          git push origin "$TAG_NAME"